### ISSUE TITLE
Test cacheDirectory 

### ISSUE THREAD

**Issue by bagart** [kefzce/CryptoCurrencyExchangesTrader#24]
[ProviderBuilderTest.php#L100](https://github.com/kefzce/CryptoCurrencyExchangesTrader/blob/50b9a81bdbda60aea3606ad9fde5ebe6f4d15b8f/tests/Provider/ProviderBuilderTest.php#L100)

`$this->cacheDirectory` ?

**Comment by kefzce** [comment]
Thanks fix on #27
